name: railseg2
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - conda-forge
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - addict=2.4.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - cpython=3.10.19
  - expat=2.7.4
  - gmp=6.3.0
  - gmpy2=2.2.1
  - importlib-metadata=8.7.0
  - jinja2=3.1.6
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.11.0
  - libcblas=3.11.0
  - libdeflate=1.22
  - libexpat=2.7.4
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libgomp=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - libnsl=2.0.0
  - libopenblas=0.3.30
  - libpng=1.6.55
  - libprotobuf=4.25.3
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libtiff=4.7.0
  - libtorch=2.1.2
  - libuuid=1.41.5
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - markdown-it-py=4.0.0
  - mdurl=0.1.2
  - mmcv=2.1.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.5
  - networkx=3.4.2
  - nomkl=1.0
  - numpy=1.26.4
  - openjpeg=2.5.3
  - openssl=3.6.1
  - packaging=25.0
  - pillow=11.3.0
  - pip=26.0.1
  - platformdirs=4.9.2
  - pthread-stubs=0.3
  - pygments=2.19.2
  - python=3.10.19
  - python_abi=3.10
  - pytorch=2.1.2
  - pyyaml=6.0.3
  - readline=8.3
  - regex=2026.2.19
  - rich=14.3.3
  - setuptools=80.10.2
  - sleef=3.9.0
  - sqlite=3.51.1
  - sympy=1.14.0
  - termcolor=3.3.0
  - tk=8.6.15
  - tomli=2.4.0
  - typing_extensions=4.15.0
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - yapf=0.43.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - filelock==3.20.0
      - fsspec==2025.12.0
      - markupsafe==3.0.2
      - mmengine==0.10.7
      - mmsegmentation==1.2.2
      - mpmath==1.3.0
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - opencv-python==4.13.0.92
      - prettytable==3.17.0
      - six==1.17.0
      - torch==2.4.1+cu124
      - torchaudio==2.4.1+cu124
      - torchvision==0.19.1+cu124
      - triton==3.0.0
      - wcwidth==0.6.0
prefix: /home/lcy/miniconda3/envs/railseg2
